name: C_Cl

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: go to 1.25
      working-directory: ./1.25
    - name: make build
      run: make Makefile build
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
