name: C1

on:
  push:
    branches: [ firstLab ]
  pull_request:
    branches: [ firstLab ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: go to 1.25 and build
      working-directory: ./1.25
      run: make Makefile build
