name: C2.2

on:
  push:
    branches: [ master ]
    paths:
      - '2.2.6/**'
  pull_request:
    branches: [ master ]
    paths:
      - '2.2.6/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build and test
      working-directory: ./2.2.6
      run: make all
    
