name: C4.2

on:
  push:
    branches: [ master ]
    paths:
      - '4.2.5/**'
  pull_request:
    branches: [ master ]
    paths:
      - '4.2.5/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install valgrind and cpplint
      run: |
        sudo apt install -y valgrind

    - name: build and test
      working-directory: ./4.2.5
      run: make all
    
