name: C5.1

on:
  push:
    branches: [ master ]
    paths:
      - '5.1.6/**'
  pull_request:
    branches: [ master ]
    paths:
      - '5.1.6/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install valgrind
      run: |
        sudo apt install -y valgrind

    - name: build and test
      working-directory: ./5.1.6
      run: make all
    
