name: C6.2

on:
  push:
    branches: [ master ]
    paths:
      - '6.2.23/**'
  pull_request:
    branches: [ master ]
    paths:
      - '6.2.23/**'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: build and test
      working-directory: ./6.2.23
      run: make all
    - name: coverage
      uses: codecov/codecov-action@v1
      with:
        files: |
          ./6.2.23/Manager.c.gcov
    
